version: '3'
services:
  db:
    container_name: fsa-apps-auth-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${PGPORT}:${PGPORT}"
volumes:
  db_data: